// Given a string, we have to find out all its subsequences of it. 
// A String is a subsequence of a given String, that is generated by deleting some character of a given string without changing its order.

#include<bits/stdc++.h>
using namespace std;

void subsequence(string input , string output){

    if(input.empty()){
        cout<<output<<"\n";
        return;
    }

    subsequence(input.substr(1),output+input[0]);
    subsequence(input.substr(1),output);

}
int main(){
    string input="abc";
    string output="";
    subsequence(input,output);
}